version: '3.6'
services:
  gateway:
      container_name: gateway
      build: ./
      stdin_open: true
      ports:
        - 3000:3000
      volumes:
        - ./:/app
        - /app/node_modules
      networks:
        - user_all-network
        - car_all-network

networks:
  user_all-network:
    external: true
  car_all-network:
    external: true
