version: '3.6'
services:

  user-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: user-db
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pwd'
    volumes:
      - user-db-data:/var/lib/mysql
    ports:
      - 3311:3306
    restart: always
    networks:
      - mailer_mailer

  user-php:
    image: ${PHP_IMAGE:-user/php}
    container_name: user-php
    build:
      context: ./app
      target: app_php
    volumes:
      - ./app:/srv/app:rw
      - ./app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - user-app-sf-cache:/srv/app/var
    networks:
      - mailer_mailer

  user-nginx:
    image: ${NGINX_IMAGE:-user/nginx}
    container_name: user-nginx
    build:
      context: ./app
      target: app_nginx
    depends_on:
      - user-php
    volumes:
      - ./app/public:/srv/app/public:ro
    ports:
      - 8095:80
    networks:
      - mailer_mailer

networks:
  mailer_mailer:
    external: true


volumes:
  user-db-data: {}
  user-app-sf-cache: {}
