version: '3.6'
x-cache-from:
  - &app-cache-from
    cache_from:
      - ${NGINX_IMAGE:-user/nginx}
      - ${PHP_IMAGE:-user/php}

services:

  user-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: user-db
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pwd'
    volumes:
      - user-db-data:/var/lib/mysql
    ports:
      - 3311:3306
    restart: always

  user-php:
    image: ${PHP_IMAGE:-user/php}
    container_name: user-php
    build:
      context: ./user/app
      target: app_php
      <<: *app-cache-from
    volumes:
      - ./user/app:/srv/app:rw
      - ./user/app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - user-app-sf-cache:/srv/app/var

  user-nginx:
    image: ${NGINX_IMAGE:-user/nginx}
    container_name: user-nginx
    build:
      context: ./user/app
      target: app_nginx
      <<: *app-cache-from
    depends_on:
      - user-php
    volumes:
      - ./user/app/public:/srv/app/public:ro
    ports:
      - 8095:80

  user-phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    container_name: user-phpmyadmin
    depends_on:
      - user-db
    ports:
      - 8096:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  user-db-data: {}
  user-app-sf-cache: {}
