version: '3.6'
services:
  stripe-php:
    image: ${PHP_IMAGE:-stripe/php}
    container_name: stripe-php
    build:
      context: ./
      target: app_php
    volumes:
      - ./:/srv/app:rw
      - ./docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - app-sf-cache:/srv/app/var

  stripe-nginx:
    image: ${NGINX_IMAGE:-stripe/nginx}
    container_name: stripe-nginx
    build:
      context: ./
      target: app_nginx
    depends_on:
      - stripe-php
    volumes:
      - ./public:/srv/app/public:ro
    ports:
      - 8110:80

volumes:
  app-sf-cache: {}
