version: '3.6'
services:

  order-db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: order-db
    environment:
      MYSQL_DATABASE: 'order'
      MYSQL_USER: 'order'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pwd'
    volumes:
      - order-db-data:/var/lib/mysql
    ports:
      - 3310:3306
    restart: always
    networks:
      - all-network

  order-php:
    image: ${PHP_IMAGE:-order/php}
    container_name: order-php
    build:
      context: ./app
      target: app_php
    volumes:
      - ./app:/srv/app:rw
      - ./app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - order-app-sf-cache:/srv/app/var
    networks:
      - all-network

  order-nginx:
    image: ${NGINX_IMAGE:-order/nginx}
    container_name: order-nginx
    build:
      context: ./app
      target: app_nginx
    depends_on:
      - order-php
    volumes:
      - ./app/public:/srv/app/public:ro
    ports:
      - 8091:80
    networks:
      - all-network

networks:
  all-network:
    driver: bridge

volumes:
  order-db-data: {}
  order-app-sf-cache: {}
