version: '3.6'
services:

  payment-db:
    platform: linux/amd64
    container_name: payment-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'payment'
      MYSQL_USER: 'payment'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pwd'
    volumes:
      - payment-db-data:/var/lib/mysql
    ports:
      - 3315:3306
    restart: always
    networks:
      - all-network

  payment-php:
    image: ${PHP_IMAGE:-payment/php}
    container_name: payment-php
    build:
      context: ./app
      target: app_php
    volumes:
      - ./app:/srv/app:rw
      - ./app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - payment-app-sf-cache:/srv/app/var
    networks:
      - all-network

  payment-nginx:
    image: ${NGINX_IMAGE:-payment/nginx}
    container_name: payment-nginx
    build:
      context: ./app
      target: app_nginx
    depends_on:
      - payment-php
    volumes:
      - ./app/public:/srv/app/public:ro
    ports:
      - 8098:80
    networks:
      - all-network

networks:
  all-network:
    driver: bridge

volumes:
  payment-db-data: {}
  payment-app-sf-cache: {}
