version: '3.6'
services:

  car-db:
    platform: linux/amd64
    container_name: car-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'car'
      MYSQL_USER: 'car'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pwd'
    volumes:
      - car-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - all-network

  car-php:
    image: ${PHP_IMAGE:-car/php}
    container_name: car-php
    build:
      context: ./app
      target: app_php
    volumes:
      - ./app:/srv/app:rw
      - ./app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - car-app-sf-cache:/srv/app/var
    networks:
      - all-network

  car-nginx:
    image: ${NGINX_IMAGE:-car/nginx}
    container_name: car-nginx
    build:
      context: ./app
      target: app_nginx
    depends_on:
      - car-php
    volumes:
      - ./app/public:/srv/app/public:ro
    ports:
      - 8081:80
    networks:
      - all-network

networks:
  all-network:
    driver: bridge

volumes:
  car-db-data: {}
  car-app-sf-cache: {}
