version: '3.6'
x-cache-from:
  - &app-cache-from
    cache_from:
      - ${NGINX_IMAGE:-car/nginx}
      - ${PHP_IMAGE:-car/php}

services:

  car-db:
    platform: linux/amd64
    container_name: car-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'car'
      MYSQL_USER: 'car'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pwd'
    volumes:
      - car-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  car-php:
    image: ${PHP_IMAGE:-car/php}
    container_name: car-php
    build:
      context: ./car/app
      target: app_php
      <<: *app-cache-from
    volumes:
      - ./car/app:/srv/app:rw
      - ./car/app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - car-app-sf-cache:/srv/app/var

  car-nginx:
    image: ${NGINX_IMAGE:-car/nginx}
    container_name: car-nginx
    build:
      context: ./car/app
      target: app_nginx
      <<: *app-cache-from
    depends_on:
      - car-php
    volumes:
      - ./car/app/public:/srv/app/public:ro
    ports:
      - 8081:80

  car-phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    container_name: car-phpmyadmin
    depends_on:
      - car-db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  car-db-data: {}
  car-app-sf-cache: {}
