FROM node:14-alpine

RUN apk --no-cache add pkgconfig autoconf automake libtool nasm build-base zlib-dev libpng-dev git

WORKDIR /car/app

COPY package.json /car/app

RUN yarn install

COPY . /car/app

EXPOSE 8101

CMD ["yarn","serve"]