version: '3.6'
services:

  booking-db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: booking-db
    environment:
      MYSQL_DATABASE: 'booking'
      MYSQL_USER: 'booking'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pwd'
    volumes:
      - booking-db-data:/var/lib/mysql
    ports:
      - 3308:3306
    restart: always
    networks:
      - all-network

  booking-php:
    image: ${PHP_IMAGE:-booking/php}
    container_name: booking-php
    build:
      context: ./app
      target: app_php
    volumes:
      - ./app:/srv/app:rw
      - ./app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - booking-app-sf-cache:/srv/app/var
    networks:
      - all-network

  booking-nginx:
    image: ${NGINX_IMAGE:-booking/nginx}
    container_name: booking-nginx
    build:
      context: ./app
      target: app_nginx
    depends_on:
      - booking-php
    volumes:
      - ./app/public:/srv/app/public:ro
    ports:
      - 8083:80
    networks:
      - all-network

networks:
  all-network:
    driver: bridge

volumes:
  booking-db-data: {}
  booking-app-sf-cache: {}
